### ISSUE TITLE
Please fix the reactions as it's not running in Dark mode

### ISSUE THREAD

**Issue by rakitanc** [SpartanJ/WhatsApp-Dark#6]
![Screenshot from 2023-08-10 00-23-01](https://github.com/SpartanJ/WhatsApp-Dark/assets/64612555/137f3201-86dc-4962-a94f-2e88987e7298)

Also the names are in white too

**Comment by SpartanJ** [comment]
Fixed.

**Comment by rakitanc** [comment]
![Screenshot from 2023-08-17 23-16-01](https://github.com/SpartanJ/WhatsApp-Dark/assets/64612555/a2138965-ffe9-40a2-8229-249a06bb7137)

When checking the group info..these white lines are showing on right side

**Comment by SpartanJ** [comment]
Fixed.

**Comment by rakitanc** [comment]
You are awesome mate. Also can you remove this screen as it looks quite odd with the style or maybe add some more minimalistic animation or whatsapp icon
![Screenshot from 2023-08-18 01-59-34](https://github.com/SpartanJ/WhatsApp-Dark/assets/64612555/f82587b9-9e58-4c9c-b88a-daf93e3b8a03)

**Comment by rakitanc** [comment]
![Screenshot from 2023-08-18 02-04-21](https://github.com/SpartanJ/WhatsApp-Dark/assets/64612555/ad46e87e-d6d5-45ff-8d3a-1ddece484825)
Also make these icons little more greener

**Comment by rakitanc** [comment]
where are you mate? was waiting for the update

**Comment by rakitanc** [comment]
> Fixed.

![Screenshot from 2023-08-26 02-00-14](https://github.com/SpartanJ/WhatsApp-Dark/assets/64612555/aff3a6a2-6db4-4e07-84ec-8057ddb3fa45)
Bug came again
